name: OwnPost
options:
  bundleIdPrefix: app.ownpost
  deploymentTarget:
    iOS: "26.0"
    macOS: "26.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Debug
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "6.2"
    SWIFT_STRICT_CONCURRENCY: complete
    SWIFT_DEFAULT_ISOLATION: MainActor
    PRODUCT_NAME: OwnPost
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    GENERATE_INFOPLIST_FILE: true

packages:
  swift-markdown:
    url: https://github.com/apple/swift-markdown.git
    from: "0.7.3"

targets:
  OwnPost:
    type: application
    platform: [iOS, macOS]
    sources:
      - path: OwnPost
        excludes:
          - "**/*.entitlements"
          - Info.plist
    resources:
      - path: OwnPost/Resources/Assets.xcassets
      - path: OwnPost/Resources/Localizable.xcstrings
    settings:
      base:
        INFOPLIST_FILE: OwnPost/Info.plist
        CODE_SIGN_ENTITLEMENTS: OwnPost/OwnPost.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: app.ownpost
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: true
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: -Onone
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O
    dependencies:
      - package: swift-markdown
        product: Markdown
    entitlements:
      path: OwnPost/OwnPost.entitlements
